blueprint:
  name: ESPHome Smart Button (v2)
  description: >
    Automatisierung f체r den ESPHome Smart Button mit Single, Double, Triple und Long Press.
  domain: automation
  input:
    esphome_device_name:
      name: ESPHome Ger채tename (devicename)
      description: Gib hier exakt den Namen ein (z.B. dw-button-12a34b).
      default: ""
    
    action_single:
      name: Einzelklick
      description: Aktion bei einfachem Klick
      default: []
      selector:
        action: {}

    action_double:
      name: Doppelklick
      description: Aktion bei doppeltem Klick
      default: []
      selector:
        action: {}

    action_triple:
      name: Dreifachklick
      description: Aktion bei dreifachem Klick
      default: []
      selector:
        action: {}

    action_long:
      name: Langer Druck
      description: Aktion bei langem Druck (>1s)
      default: []
      selector:
        action: {}

trigger:
  - platform: event
    event_type: esphome.button_action

# HIER WAR DER FEHLER: Wir m체ssen den Input in eine Variable mappen
variables:
  # Wir holen den Wert aus dem Input und speichern ihn in einer Variable f체r das Template
  target_device: !input esphome_device_name

condition:
  - condition: template
    # Jetzt vergleichen wir mit der Variable 'target_device' statt dem Input direkt
    value_template: "{{ trigger.event.data.device_id == target_device }}"

action:
  - choose:
      # Single Click
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.action == 'single_click' }}"
        sequence: !input action_single
      
      # Double Click
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.action == 'double_click' }}"
        sequence: !input action_double

      # Triple Click
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.action == 'triple_click' }}"
        sequence: !input action_triple

      # Long Press
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.action == 'long_press' }}"
        sequence: !input action_long
