esphome:
  name: smart-button
  name_add_mac_suffix: true
  
  friendly_name: "Smart Button"

  project:
    name: "diy.smart_button_esp8266"
    version: "1.0"

esp8266:
  # Wähle hier dein Board:
  # d1_mini (für Wemos D1 Mini)
  # nodemcuv2 (für NodeMCU)
  board: d1_mini

logger:

api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Smart Button Fallback"
    password: "1234"

captive_portal:

#############################################################
# BUTTON LOGIK
#############################################################

binary_sensor:
  - platform: gpio
    id: multi_click_button
    name: "Multifunktions Taster"
    pin:
      number: D1
      mode:
        input: true
        pullup: true
      inverted: true # Taster schaltet gegen GND
    
    filters:
      # Entprellen (Debouncing)
      - delayed_on: 10ms
      - delayed_off: 10ms

    on_multi_click:
      # -----------------------------------------------------
      # 1. TRIPLE PRESS (Dreifach-Klick)
      # -----------------------------------------------------
      - timing:
          - ON for at most 1s
          - OFF for at most 1s
          - ON for at most 1s
          - OFF for at most 1s
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - logger.log: "Dreifach-Klick erkannt!"
          # Sende ein Event an Home Assistant
          - homeassistant.event:
              event_type: esphome.button_action
              data:
                action: triple_click
                device: smart_button_8266

      # -----------------------------------------------------
      # 2. DOUBLE PRESS (Doppel-Klick)
      # -----------------------------------------------------
      - timing:
          - ON for at most 1s
          - OFF for at most 1s
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - logger.log: "Doppel-Klick erkannt!"
          - homeassistant.event:
              event_type: esphome.button_action
              data:
                action: double_click
                device: smart_button_8266

      # -----------------------------------------------------
      # 3. SINGLE PRESS (Einzel-Klick)
      # -----------------------------------------------------
      - timing:
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - logger.log: "Einzel-Klick erkannt!"
          - homeassistant.event:
              event_type: esphome.button_action
              data:
                action: single_click
                device: smart_button_8266

      # -----------------------------------------------------
      # 4. LONG PRESS (Langer Druck > 1 Sekunde)
      # -----------------------------------------------------
      - timing:
          - ON for at least 1s
        then:
          - logger.log: "Langer Druck erkannt!"
          - homeassistant.event:
              event_type: esphome.button_action
              data:
                action: long_press
                device: smart_button_8266
