substitutions:
  devicename: "smart-button"
  button_pin: D1 
  inverted: "true"

esphome:
  name: ${devicename}
  name_add_mac_suffix: true
  project:
    name: "user.generic_button"
    version: "1.0"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Fallback Hotspot"
    password: "fallback_pass"

api:

ota:
  - esphome

logger:

binary_sensor:
  - platform: gpio
    id: main_button
    name: "Button"
    pin:
      number: ${button_pin}
      mode:
        input: true
        pullup: true
      inverted: ${inverted}
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms

    on_multi_click:
      # Triple Click
      - timing:
          - ON for at most 1s
          - OFF for at most 1s
          - ON for at most 1s
          - OFF for at most 1s
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - logger.log: "Dreifach-Klick"
          - homeassistant.event:
              event: esphome.button_action
              data:
                action: triple_click
                device_id: !lambda 'return id(main_button).get_object_id();'

      # Double Click
      - timing:
          - ON for at most 1s
          - OFF for at most 1s
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - logger.log: "Doppel-Klick"
          - homeassistant.event:
              event: esphome.button_action
              data:
                action: double_click
                device_id: !lambda 'return id(main_button).get_object_id();'

      # Single Click
      - timing:
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - logger.log: "Einzel-Klick"
          - homeassistant.event:
              event: esphome.button_action
              data:
                action: single_click
                device_id: !lambda 'return id(main_button).get_object_id();'

      # Long Press
      - timing:
          - ON for at least 1s
        then:
          - logger.log: "Langer Druck"
          - homeassistant.event:
              event: esphome.button_action
              data:
                action: long_press
                device_id: !lambda 'return id(main_button).get_object_id();'
